package com.mycompany.myapp;

import com.mycompany.myapp.Controllers.ComplaintController;
import com.mycompany.myapp.Forms.*;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;
import java.io.IOException;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.util.UIBuilder;
import com.mycompany.myapp.Entities.SimpleUser;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
    private Form current;
    public static Form mainForm;
    private Button exitBtn,loginFacebookBtn,loginBtn,registerBtn;
    private Container mainContainer;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        if (SimpleUser.getSplash()==0){
         try {
            SplashScreen sps = new SplashScreen();
            sps.show();
        } catch (IOException ex) {
           
        }
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {generateMenu();
            SimpleUser.setSplash(1);
            }}, 4000 );}
        else {generateMenu();}

    }
public void generateMenu()
{
    
    if (!(SimpleUser.isAuth())){
    
        theme = UIManager.initFirstTheme("/theme");
        UIBuilder ui = new UIBuilder();
        exitBtn = new Button("Exit");
        exitBtn.getUnselectedStyle().setFgColor(5542241);
        loginFacebookBtn = new Button(theme.getImage("fblogin3.png"));
        loginFacebookBtn.setUIID("CenterLabel");

        loginBtn = new Button("Login");
        loginBtn.getUnselectedStyle().setFgColor(5542241);
        registerBtn = new Button("Register");
        registerBtn.getUnselectedStyle().setFgColor(5542241);
        
        mainContainer = new Container();
        mainContainer.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        mainContainer.add(loginFacebookBtn);
        mainContainer.add(loginBtn);
        mainContainer.add(registerBtn);
        mainContainer.add(exitBtn);
        mainForm=new Form();
        mainForm.setLayout(new BorderLayout());
        mainForm.add(BorderLayout.CENTER,mainContainer);
        
        loginBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new Login().show();
            }
        });
        registerBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new RegisterForm().show();
            }
        });
        loginFacebookBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {                
                new FacebookMain().start();
            }
        });
        exitBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                        Display.getInstance().exitApplication();
            }
        });
        

        mainForm.show();
    }
    else {
        new MenuForm().show();
    }
}
    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
